### ISSUE TITLE
[Suggestion] Discard the the last 1.9MB video fragment from Youku

### ISSUE THREAD

**Issue by woodword** [soimort/you-get#1405]
Recently Youku automatically adds a 1.9 MB (1,883,240 bytes)  / 6 seconds video fragment behind the every video (at least for the videos I subscribed) uploaded by users. If you use "-n" / "--no-merge" switch you would find it's a commercial and quite annoying. 

What is worse is this fragment seems always be in 1920 x 1080 resolution, so if the video uploaded by the user is not in the same resolution it would lead to a merging failure. 

Please add some codes so that you-get could detect this fragment (md5 hash ?) and not download or try to merge it.

Some examples:
http://v.youku.com/v_show/id_XMTYyNjg5MTQwOA==.html
http://v.youku.com/v_show/id_XMTcyODYzMDQwOA==.html
http://v.youku.com/v_show/id_XMTYzNzg3NjkyNA==.html

---------------------------------------------------------------------------------------------------------------
UPDATE: After further test, it seems that the "fail to merge" error only happens to some old videos. For the newly uploaded ones Youku can choose the correct resolution for this 6-second commercial.

---------------------------------------------------------------------------------------------------------------
UPDATE: After I reinstalled the FFmpeg I can merge the 1920 x 1080 commercial, so it is only a suggestion for you-get now to discard the last 1.9MB video fragment. 
    This could be implemented by probing the duration of all downloaded fragments (ffprobe) and discarding those shorter than a few seconds, like 10 seconds, or, as @Erk- suggested,  ignoring all the videos fragments from certain addresses such as vali.cp31.ott.cibntv.net.

**Comment by lamlam123tld3** [comment]
i dont get this problem er

**Comment by woodword** [comment]
You mean you didn't get the last 6 seconds commercial , or you got it but you can merge it ?

**Comment by Erk-** [comment]
The commercial comes from the url http://vali.cp31.ott.cibntv.net for me in both of your examples. I can merge it. Can you post your output of the "you-get --json http://v.youku.com/v_show/id_XMTcyODYzMDQwOA==.html".

**Comment by Erk-** [comment]
I have created a fix but I am not sure it works on all urls #1407

**Comment by lamlam123tld3** [comment]
for me,
i totally do not got this issues,
maybe becuz of my overseas IP?


a better method that may fix it
remove yxon  = 1 on line 307
to directly get the file link
instead of going through youku server



`q = parse.urlencode(dict(
                            ctype = self.ctype,
                            ev    = 1,
                            K     = k,
                            ep    = parse.unquote(ep),
                            oip   = str(self.ip),
                            token = token,
                            yxon  = 1
                        ))
                        u = 'http://k.youku.com/player/getFlvPath/sid/{sid}_00' \
                            '/st/{container}/fileid/{fileid}?{q}'.format(
                                sid       = sid,
                                container = self.streams[stream_id]['container'],
                                fileid    = fileid,
                                q         = q
                            )
                        ksegs += u`

**Comment by woodword** [comment]
@Erk-  You are right. It comes from vali.cp31.ott.cibntv.net
```
{
    "site": "优酷 (Youku)",
    "streams": {
        "flvhd": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030002010057DD4A292F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                    "segs": [
                        {
                            "fileid": "030002010057DD4A292F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                            "key": "d6927881e1afa39c261f3ea2",
                            "size": "9476603",
                            "total_milliseconds_audio": "180373",
                            "total_milliseconds_video": "181533"
                        }
                    ]
                },
                {
                    "fileid": "03000201005756ACF08896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                    "segs": [
                        {
                            "fileid": "03000201005756ACF08896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                            "key": "c033913cb7426f182412bf2e",
                            "size": "1212064",
                            "total_milliseconds_audio": "6641",
                            "total_milliseconds_video": "6400"
                        }
                    ]
                }
            ],
            "size": 10688667,
            "video_profile": "标清"
        },
        "hd2": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                    "segs": [
                        {
                            "fileid": "030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                            "key": "1e8cd4531d48da9b282bbe16",
                            "size": "36986191",
                            "total_milliseconds_audio": "180326",
                            "total_milliseconds_video": "181448"
                        }
                    ]
                },
                {
                    "fileid": "03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                    "segs": [
                        {
                            "fileid": "03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                            "key": "974e6c65b111127a2412bf2e",
                            "size": "1883240",
                            "total_milliseconds_audio": "6571",
                            "total_milliseconds_video": "6360"
                        }
                    ]
                }
            ],
            "size": 38869431,
            "src": [
                "http://103.38.56.104/youku/6971E718D0E3B7A1337BA62E4/030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2.flv",
                "http://vali.cp31.ott.cibntv.net/youku/6572BFE8AD237715171422C75/03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109.flv"
            ],
            "video_profile": "超清"
        },
        "mp4": {
            "container": "mp4",
            "pieces": [
                {
                    "fileid": "030008010057DD4BA02F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                    "segs": [
                        {
                            "fileid": "030008010057DD4BA02F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                            "key": "9b38d91d48db35032412bf2e",
                            "size": "19596190",
                            "total_milliseconds_audio": "180373",
                            "total_milliseconds_video": "181448"
                        }
                    ]
                },
                {
                    "fileid": "03000801005756AC828896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                    "segs": [
                        {
                            "fileid": "03000801005756AC828896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                            "key": "d103d99ae9c2f80e261f3ea2",
                            "size": "1842423",
                            "total_milliseconds_audio": "6641",
                            "total_milliseconds_video": "6360"
                        }
                    ]
                }
            ],
            "size": 21438613,
            "video_profile": "高清"
        }
    },
    "title": "恐怖游戏里的洗脑神曲【虐魔奶奶】",
    "url": "http://v.youku.com/v_show/id_XMTcyODYzMDQwOA==.html"
}

```

**Comment by soimort** [comment]
Fixed by #1407.

**Comment by JayXon** [comment]
I'm using 0.4.555 but still having this issue, probably youku changed the url, it's an ip instead of cibntv.net for me.
```
λ you-get -dt 3 --json http://v.youku.com/v_show/id_XMTcyODYzMDQwOA==.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTcyODYzMDQwOA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTcyODYzMDQwOA==&ct=12
[DEBUG] request attempt 1 timeout
[DEBUG] request attempt 2 timeout
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/647726945021712b30d89_00/st/flv/fileid/030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2?oip=847826864&token=2939&ctype=12&yxon=1&ep=dCaTHUuLX8oF5SHejz8bNS%2FiIH8GXP4J9h%2BFgNJjALshT5zLnU3Qs5%2FGTYxCEv4QdyVzY%2BiF2tPuGENlYYJE3WAQ302rOPrjjYGV5dtUx%2BVzYBlEA7ultlScSjP4&ev=1&K=131261bb6ae98ae1261f4eb3
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/647726945021712b30d89_00/st/flv/fileid/03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109?oip=847826864&token=2939&ctype=12&yxon=1&ep=dCaTHUuLX8oF5SHejz8bNS%2FiIH8GXP4J9h%2BFgNJjALshT%2B256E2lxpW4R%2FlCFvkZcSB1GOyEqaKSY0FlYflE324Q3jurS%2FqR%2BPPn5dknseV1YhFDAMzXvVScSjP4&ev=1&K=1216b30bf311c3762412c8d1
{
    "site": "优酷 (Youku)",
    "streams": {
        "flvhd": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030002010057DD4A292F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                    "segs": [
                        {
                            "fileid": "030002010057DD4A292F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                            "key": "5d20877e19f00139261f4eb3",
                            "size": "9476603",
                            "total_milliseconds_audio": "180373",
                            "total_milliseconds_video": "181533"
                        }
                    ]
                },
                {
                    "fileid": "03000201005756ACF08896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                    "segs": [
                        {
                            "fileid": "03000201005756ACF08896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                            "key": "2267a0fdfb6d61eb261f4eb3",
                            "size": "1212064",
                            "total_milliseconds_audio": "6641",
                            "total_milliseconds_video": "6400"
                        }
                    ]
                }
            ],
            "size": 10688667,
            "video_profile": "标清"
        },
        "hd2": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                    "segs": [
                        {
                            "fileid": "030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                            "key": "131261bb6ae98ae1261f4eb3",
                            "size": "36986191",
                            "total_milliseconds_audio": "180326",
                            "total_milliseconds_video": "181448"
                        }
                    ]
                },
                {
                    "fileid": "03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                    "segs": [
                        {
                            "fileid": "03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                            "key": "1216b30bf311c3762412c8d1",
                            "size": "1883240",
                            "total_milliseconds_audio": "6571",
                            "total_milliseconds_video": "6360"
                        }
                    ]
                }
            ],
            "size": 38869431,
            "src": [
                "http://103.38.56.104/youku/67718096F444A7CAF2C4540D7/030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2.flv",
                "http://103.38.59.42/youku/69759988929437B7882DD4394/03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109.flv"
            ],
            "video_profile": "超清"
        },
        "mp4": {
            "container": "mp4",
            "pieces": [
                {
                    "fileid": "030008010057DD4BA02F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                    "segs": [
                        {
                            "fileid": "030008010057DD4BA02F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2",
                            "key": "0d249870115aafe4282bd494",
                            "size": "19596190",
                            "total_milliseconds_audio": "180373",
                            "total_milliseconds_video": "181448"
                        }
                    ]
                },
                {
                    "fileid": "03000801005756AC828896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                    "segs": [
                        {
                            "fileid": "03000801005756AC828896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109",
                            "key": "4c46a6a050e14ccd2412c8d1",
                            "size": "1842423",
                            "total_milliseconds_audio": "6641",
                            "total_milliseconds_video": "6360"
                        }
                    ]
                }
            ],
            "size": 21438613,
            "video_profile": "高清"
        }
    },
    "title": "恐怖游戏里的洗脑神曲【虐魔奶奶】",
    "url": "http://v.youku.com/v_show/id_XMTcyODYzMDQwOA==.html"
}
```

**Comment by Erk-** [comment]
@JayXon Can you try to run you-get -n http://v.youku.com/v_show/id_XMTcyODYzMDQwOA==.html and see if you get both files. If you run you-get normally you do not download the file, i do not know why it is still shown in the json, but I will look into it.

**Comment by JayXon** [comment]
@Erk- I tried that and it downloaded two files:
恐怖游戏里的洗脑神曲【虐魔奶奶】[00].flv
恐怖游戏里的洗脑神曲【虐魔奶奶】[01].flv
The second one is 1.79 MB (1,883,240 bytes) and it's an ad.

**Comment by soimort** [comment]
In @JayXon's case:

```json
"src": [
    "http://103.38.56.104/youku/67718096F444A7CAF2C4540D7/030001010057DD4C1D2F3C047957EC3DA39B3A-B7D8-0331-3CAF-F73EC60BAFB2.flv",
    "http://103.38.59.42/youku/69759988929437B7882DD4394/03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109.flv"
],
```

The commercial (second piece) came from 103.38.59.42. There's no way to decide this solely by its IP or domain. I'm reopening this issue.

**Comment by Erk-** [comment]
could it be possible that the file is always called: "03000101005756ACD18896000032C87E2BE91A-97F6-1E3B-A634-DDEEE48EB109.flv" it is in both cases here. And in the example given by @woodword in #1432  the file also exist.

**Comment by JayXon** [comment]
Here's another case where the first one is a 15 seconds ad.
It seems to me that there's always two pieces in json if there's an ad (only one piece if no ad), and the shorter piece is the ad.

```
λ you-get -dt 3 --json http://v.youku.com/v_show/id_XNTAwNDM0ODI0.html
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNTAwNDM0ODI0&ct=10
[DEBUG] request attempt 1 timeout
[DEBUG] request attempt 2 timeout
[DEBUG] request attempt 3 timeout
[DEBUG] request attempt 4 timeout
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XNTAwNDM0ODI0&ct=12
[DEBUG] request attempt 1 timeout
[DEBUG] request attempt 2 timeout
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080010057BDA97A95410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdJjALshT5rL6DfWtpS1Sv5CEf0bBiByYZnwr9DgbzMdYfJLrW0Q3EahTPrpiIKV5axRxOMDE202cM%2BmxlSdQDL4&K=4b8225f8131b4a67282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100055281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiALshTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=ed90bea3925ba80c261f5296&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100155281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiALohTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=199f3e19cf9f7235282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100255281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiALkhTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=1bac3b0047258dd0282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100355281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiALghTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=d6111f41fbdd4157282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100455281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAL8hTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=b12b12d0a1ba35cf261f5296&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100555281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAL4hTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=94dad894038ad59c282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100655281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAL0hTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=4756d34f0e4de05d282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100755281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiALwhTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=7567e1b114e11d7e261f5296&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100855281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiALMhTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=8233b3f1275321b1282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100955281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiALIhTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=b13e2f8194f68232282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100A55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAMohTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=8de5191b924de25b282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100B55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAMkhTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=e98045bf8b1ecb73282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100C55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAMghTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=2e04750ac05ec8f12412cb27&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100D55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAM8hTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=4eb29e8373829a882412cb27&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100E55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAM4hTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=ec2799af8b85895a282bda05&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/7477986028165128d61e3_00/st/flv/fileid/030080100F55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB?ep=dSaTHUCFUM4C7SLZjT8bb3jkdSIMXP4J9h%2BNgdNiAM0hTeq3mEuntZmwRvZCEPscdVB0Fuz4q6OSGDZhYfZHrRwQ2kuoPPrp%2B%2Fnq5dlSt5ADYm9FAbmixlSdQDL4&K=b2eed3c3ce17d9a62412cb27&ctype=12&token=3329&ev=1&yxon=1&oip=847826864
{
    "site": "优酷 (Youku)",
    "streams": {
        "flvhd": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030002010057BDA87B95410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                    "segs": [
                        {
                            "fileid": "030002010057BDA87B95410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                            "key": "fde77aeb305cba39282bda05",
                            "size": "792774",
                            "total_milliseconds_audio": "15139",
                            "total_milliseconds_video": "15133"
                        }
                    ]
                },
                {
                    "fileid": "03000206005527CE9B408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                    "segs": [
                        {
                            "fileid": "03000206005527CE9B408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "313850ab9d68863b2412cb27",
                            "size": "22908878",
                            "total_milliseconds_audio": "408067",
                            "total_milliseconds_video": "408067"
                        },
                        {
                            "fileid": "03000206015527CE9B408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "65f4259d69859504261f5296",
                            "size": "12075862",
                            "total_milliseconds_audio": "401799",
                            "total_milliseconds_video": "401800"
                        },
                        {
                            "fileid": "03000206025527CE9B408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "5adb5b31ac9470c7261f5296",
                            "size": "14126844",
                            "total_milliseconds_audio": "419398",
                            "total_milliseconds_video": "419400"
                        },
                        {
                            "fileid": "03000206035527CE9B408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "0c0f3e2845b0f288261f5296",
                            "size": "14608205",
                            "total_milliseconds_audio": "415405",
                            "total_milliseconds_video": "415400"
                        },
                        {
                            "fileid": "03000206045527CE9B408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "4217fd2a0702041a282bda05",
                            "size": "8599113",
                            "total_milliseconds_audio": "232200",
                            "total_milliseconds_video": "232200"
                        },
                        {
                            "fileid": "03000206055527CE9B408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "ddb1bea28b97b15c282bda05",
                            "size": "5352061",
                            "total_milliseconds_audio": "287370",
                            "total_milliseconds_video": "287333"
                        }
                    ]
                }
            ],
            "size": 78463737,
            "video_profile": "标清"
        },
        "hd2": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030001010057BDA95695410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                    "segs": [
                        {
                            "fileid": "030001010057BDA95695410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                            "key": "a20f3b63e9d5acc1282bda05",
                            "size": "3110595",
                            "total_milliseconds_audio": "15093",
                            "total_milliseconds_video": "15040"
                        }
                    ]
                },
                {
                    "fileid": "0300010C005527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                    "segs": [
                        {
                            "fileid": "0300010C005527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "91a93dcf8c5f457b2412cb27",
                            "size": "40024322",
                            "total_milliseconds_audio": "180280",
                            "total_milliseconds_video": "180280"
                        },
                        {
                            "fileid": "0300010C015527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "50f88bd022a6739e282bda05",
                            "size": "40690984",
                            "total_milliseconds_audio": "181487",
                            "total_milliseconds_video": "181480"
                        },
                        {
                            "fileid": "0300010C025527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "ff048bf5bdc6df60261f5296",
                            "size": "28569199",
                            "total_milliseconds_audio": "206472",
                            "total_milliseconds_video": "206480"
                        },
                        {
                            "fileid": "0300010C035527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "0a9437636cfe15482412cb27",
                            "size": "21720011",
                            "total_milliseconds_audio": "195837",
                            "total_milliseconds_video": "195840"
                        },
                        {
                            "fileid": "0300010C045527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "03a0c260a95e0c35282bda05",
                            "size": "34680805",
                            "total_milliseconds_audio": "205450",
                            "total_milliseconds_video": "205440"
                        },
                        {
                            "fileid": "0300010C055527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "048af3c2267cbb47261f5296",
                            "size": "23598360",
                            "total_milliseconds_audio": "184274",
                            "total_milliseconds_video": "184280"
                        },
                        {
                            "fileid": "0300010C065527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "65beceacb867b9e32412cb27",
                            "size": "27662544",
                            "total_milliseconds_audio": "196719",
                            "total_milliseconds_video": "196720"
                        },
                        {
                            "fileid": "0300010C075527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "9018a419f864fada282bda05",
                            "size": "35275241",
                            "total_milliseconds_audio": "187199",
                            "total_milliseconds_video": "187200"
                        },
                        {
                            "fileid": "0300010C085527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "bd6acdb0018b220a282bda05",
                            "size": "19819159",
                            "total_milliseconds_audio": "190079",
                            "total_milliseconds_video": "190080"
                        },
                        {
                            "fileid": "0300010C095527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "76e4815164116de5282bda05",
                            "size": "32545504",
                            "total_milliseconds_audio": "180001",
                            "total_milliseconds_video": "180000"
                        },
                        {
                            "fileid": "0300010C0A5527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "8521c1131adea161282bda05",
                            "size": "11193633",
                            "total_milliseconds_audio": "140759",
                            "total_milliseconds_video": "140760"
                        },
                        {
                            "fileid": "0300010C0B5527FAF0408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "5d9c35f5a420f5342412cb27",
                            "size": "8875209",
                            "total_milliseconds_audio": "115682",
                            "total_milliseconds_video": "115640"
                        }
                    ]
                }
            ],
            "size": 327765566,
            "video_profile": "超清"
        },
        "hd3": {
            "container": "flv",
            "pieces": [
                {
                    "fileid": "030080010057BDA97A95410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                    "segs": [
                        {
                            "fileid": "030080010057BDA97A95410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                            "key": "4b8225f8131b4a67282bda05",
                            "size": "5939566",
                            "total_milliseconds_audio": "15093",
                            "total_milliseconds_video": "15040"
                        }
                    ]
                },
                {
                    "fileid": "030080100055281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                    "segs": [
                        {
                            "fileid": "030080100055281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "ed90bea3925ba80c261f5296",
                            "size": "59536359",
                            "total_milliseconds_audio": "141479",
                            "total_milliseconds_video": "141480"
                        },
                        {
                            "fileid": "030080100155281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "199f3e19cf9f7235282bda05",
                            "size": "67720732",
                            "total_milliseconds_audio": "134003",
                            "total_milliseconds_video": "134000"
                        },
                        {
                            "fileid": "030080100255281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "1bac3b0047258dd0282bda05",
                            "size": "49556289",
                            "total_milliseconds_audio": "121719",
                            "total_milliseconds_video": "121720"
                        },
                        {
                            "fileid": "030080100355281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "d6111f41fbdd4157282bda05",
                            "size": "31954526",
                            "total_milliseconds_audio": "140759",
                            "total_milliseconds_video": "140760"
                        },
                        {
                            "fileid": "030080100455281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "b12b12d0a1ba35cf261f5296",
                            "size": "27251824",
                            "total_milliseconds_audio": "147122",
                            "total_milliseconds_video": "147120"
                        },
                        {
                            "fileid": "030080100555281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "94dad894038ad59c282bda05",
                            "size": "40106320",
                            "total_milliseconds_audio": "139319",
                            "total_milliseconds_video": "139320"
                        },
                        {
                            "fileid": "030080100655281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "4756d34f0e4de05d282bda05",
                            "size": "39165736",
                            "total_milliseconds_audio": "135280",
                            "total_milliseconds_video": "135280"
                        },
                        {
                            "fileid": "030080100755281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "7567e1b114e11d7e261f5296",
                            "size": "38494942",
                            "total_milliseconds_audio": "148398",
                            "total_milliseconds_video": "148400"
                        },
                        {
                            "fileid": "030080100855281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "8233b3f1275321b1282bda05",
                            "size": "33234835",
                            "total_milliseconds_audio": "136441",
                            "total_milliseconds_video": "136440"
                        },
                        {
                            "fileid": "030080100955281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "b13e2f8194f68232282bda05",
                            "size": "41170730",
                            "total_milliseconds_audio": "124761",
                            "total_milliseconds_video": "124760"
                        },
                        {
                            "fileid": "030080100A55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "8de5191b924de25b282bda05",
                            "size": "40177035",
                            "total_milliseconds_audio": "135836",
                            "total_milliseconds_video": "135840"
                        },
                        {
                            "fileid": "030080100B55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "e98045bf8b1ecb73282bda05",
                            "size": "43508467",
                            "total_milliseconds_audio": "149885",
                            "total_milliseconds_video": "149880"
                        },
                        {
                            "fileid": "030080100C55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "2e04750ac05ec8f12412cb27",
                            "size": "33722386",
                            "total_milliseconds_audio": "141038",
                            "total_milliseconds_video": "141040"
                        },
                        {
                            "fileid": "030080100D55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "4eb29e8373829a882412cb27",
                            "size": "49447684",
                            "total_milliseconds_audio": "149397",
                            "total_milliseconds_video": "149400"
                        },
                        {
                            "fileid": "030080100E55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "ec2799af8b85895a282bda05",
                            "size": "19308163",
                            "total_milliseconds_audio": "108484",
                            "total_milliseconds_video": "108480"
                        },
                        {
                            "fileid": "030080100F55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "b2eed3c3ce17d9a62412cb27",
                            "size": "16139328",
                            "total_milliseconds_audio": "110272",
                            "total_milliseconds_video": "110280"
                        }
                    ]
                }
            ],
            "size": 636434922,
            "src": [
                "http://103.38.56.11/youku/657298C0F8E457BD0DFB54E75/030080010057BDA97A95410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB.flv",
                "http://103.38.56.79/youku/6774C27EF7930782AC539394E/030080100055281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.110/youku/697723BDA964D7D34DB2F4B58/030080100155281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.21/youku/677658A85CD3779621D2C43A7/030080100255281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.58/youku/677723BD5794D7D34CBBF2FF4/030080100355281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.129/youku/6777EED2B3B30782ACE67475B/030080100455281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.26/youku/657723BDD01407AF2789924AF/030080100555281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.50/youku/677984FC4B53B7A1412F124D5/030080100655281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.158/youku/6578B9E7CE73779623A122542/030080100755281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.32/youku/697CB150C054E7D613FDF3EC1/030080100855281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.72/youku/677BE63B8A5457BD0EFE939E4/030080100955281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.98/youku/657B1B26A42407AF28A513295/030080100A55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.71/youku/657BE63BA00327883BBBF4E04/030080100B55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.82/youku/657CB150F6E367935AE003AB3/030080100C55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.62/youku/677F128F822467BFD6937623A/030080100D55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.14/youku/657E477A7613478DCA8613459/030080100E55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv",
                "http://103.38.56.89/youku/67810A8B9A574C7D0858E2314A/030080100F55281EFB408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB.flv"
            ],
            "video_profile": "1080P"
        },
        "mp4": {
            "container": "mp4",
            "pieces": [
                {
                    "fileid": "030008010057BDA94295410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                    "segs": [
                        {
                            "fileid": "030008010057BDA94295410742D2DAB14075C9-2845-389E-9FBF-120C3ED022AB",
                            "key": "e4bd4e0561d1d6c72412cb27",
                            "size": "1638271",
                            "total_milliseconds_audio": "15139",
                            "total_milliseconds_video": "15040"
                        }
                    ]
                },
                {
                    "fileid": "03000806005527EC53408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                    "segs": [
                        {
                            "fileid": "03000806005527EC53408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "7c94b48e3cfd90fb261f5296",
                            "size": "44039352",
                            "total_milliseconds_audio": "406999",
                            "total_milliseconds_video": "407000"
                        },
                        {
                            "fileid": "03000806015527EC53408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "584baf96d531377c261f5296",
                            "size": "20760137",
                            "total_milliseconds_audio": "386520",
                            "total_milliseconds_video": "386520"
                        },
                        {
                            "fileid": "03000806025527EC53408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "f2603919158407092412cb27",
                            "size": "23632860",
                            "total_milliseconds_audio": "360281",
                            "total_milliseconds_video": "360280"
                        },
                        {
                            "fileid": "03000806035527EC53408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "d3f4b4708997a14a2412cb27",
                            "size": "28382774",
                            "total_milliseconds_audio": "391442",
                            "total_milliseconds_video": "391440"
                        },
                        {
                            "fileid": "03000806045527EC53408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "b4423182f7e41b922412cb27",
                            "size": "18081371",
                            "total_milliseconds_audio": "288438",
                            "total_milliseconds_video": "288440"
                        },
                        {
                            "fileid": "03000806055527EC53408906257BB6790CEBFE-644D-5505-9599-D1C034FCCDEB",
                            "key": "e3a63ad689158af82412cb27",
                            "size": "13421274",
                            "total_milliseconds_audio": "330559",
                            "total_milliseconds_video": "330520"
                        }
                    ]
                }
            ],
            "size": 149956039,
            "video_profile": "高清"
        }
    },
    "title": "李阳导演作品《坏未来》（16岁以下不宜观看）",
    "url": "http://v.youku.com/v_show/id_XNTAwNDM0ODI0.html"
}
```
